(define (gallery-date entries)
  (car (sort
         (map (lambda (entry) (field entry "capturedAt")) entries)
         (lambda (a b) (string<? (substring a 0 19) (substring b 0 19))))))

(define (prepare-gallery directory)
  (define gallery (read-json-file (string-append directory "/metadata.json")))
  (define entries (map (lambda (item)
                         (append (list (cons "file" (published-filename (field item "file")))
                                       (assoc "alt" item)
                                       (cons "directory" directory))
                                 (read-metadata (string-append directory "/" (field item "file")))))
                       (field gallery "items")))
  (list (cons "title" (field gallery "title"))
        (cons "lang" (field gallery "lang"))
        (cons "description" (field gallery "description"))
        (cons "location" (field gallery "location"))
        (cons "directory" directory)
        (cons "date" (gallery-date entries))
        (cons "entries" entries)))

(define (prepare-galleries)
  (sort (map (lambda (name)
               (prepare-gallery (string-append "photos/" name)))
             (directory-file-names "photos"))
        (lambda (a b)
          (string>? (substring (field a "date") 0 19)
                    (substring (field b "date") 0 19)))))

(define (render-gallery-entry entry)
  (let ((url (string-append "/" (field entry "directory") "/" (field entry "file")))
        (alt (field entry "alt"))
        (width (field entry "width"))
        (height (field entry "height")))
    (if (string=? (field entry "type") "image")
      `(img (@ (src ,url)
               (alt ,alt)
               (width ,width)
               (height ,height)
               (loading "lazy")))
      `(div (@ (class "video"))
            (video (@ (src ,url)
                      (poster ,(string-append "/" (field entry "directory") "/" (field entry "poster")))
                      (aria-label ,alt)
                      (width ,width)
                      (height ,height)
                      (loading "lazy")
                      (playsinline)))
            (button (@ (class "overlay") (type "button") (lang "en")) "Play")))))

(define (render-gallery gallery)
  (let ((title (field gallery "title"))
        (description (field gallery "description"))
        (location (field gallery "location"))
        (date (field gallery "date"))
        (entries (field gallery "entries")))
    (render-page title (field gallery "lang")
      `(body
         ,header
         (main (@ (class "photo-gallery"))
               (header
                 (h1 ,title)
                 (p ,description)
                 (p (@ (class "gallery-metadata")) ,location " · ",(render-date date)))
               (div ,@(map render-gallery-entry entries)))))))

(define (render-gallery-preview gallery)
  (let* ((entries (field gallery "entries"))
         (cover (car entries))
         (file (field cover (if (string=? (field cover "type") "video") "poster" "file")))
         (date (field gallery "date")))
    `(li (@ (lang ,(field gallery "lang")))
       (a (@ (class "gallery-preview")
             (href ,(string-append "/" (field gallery "directory") ".html")))
          (img (@ (src ,(string-append "/" (field cover "directory") "/" file))
                  (alt ,(field cover "alt"))
                  (width ,(field cover "width"))
                  (height ,(field cover "height"))
                  (loading "lazy")))
          (div (@ (class "overlay"))
               (h2 ,(field gallery "title"))
               ,(render-date date))))))

(define (render-photos-index galleries)
  (render-page "Photos" "en"
    `(body
       ,header
       (main (@ (class "photos-index"))
             (ul ,@(map render-gallery-preview galleries))))))
