(define (write-html path document)
  (call-with-output-file path
    (lambda (port)
      (define (write-text value)
        (string-for-each
          (lambda (character)
            (display
              (case character
                ((#\&) "&amp;")
                ((#\<) "&lt;")
                ((#\>) "&gt;")
                ((#\") "&quot;")
                ((#\') "&#39;")
                (else (string character)))
              port))
          (if (number? value) (number->string value) value)))

      (define (write-attribute attribute)
        (when (or (null? (cdr attribute)) (cadr attribute))
          (display " " port)
          (display (car attribute) port)
          (unless (null? (cdr attribute))
            (display "=\"" port)
            (write-text (cadr attribute))
            (display "\"" port))))

      (define (write-node node)
        (cond
          ((not node) #f)
          ((and (pair? node) (eq? (car node) 'raw))
           (display (cadr node) port))
          ((pair? node)
           (let* ((tag (car node))
                  (body (cdr node))
                  (attributes? (and (pair? body) (pair? (car body))
                                    (eq? (caar body) '@)))
                  (attributes (if attributes? (cdar body) '()))
                  (children (if attributes? (cdr body) body)))
             (display "<" port)
             (display tag port)
             (for-each write-attribute attributes)
             (display ">" port)
             (unless (memq tag '(area base br col embed hr img input link meta
                                param source track wbr))
               (for-each write-node children)
               (display "</" port)
               (display tag port)
               (display ">" port))))
          (else (write-text node))))

      (port/set-coding port 'utf-8)
      (display "<!doctype html>\n" port)
      (write-node document)
      (newline port))))
