(define (field object name)
  (cdr (assoc name object)))

(define (read-json-file path)
  (call-with-input-file
    path
    (lambda (port)
      (port/set-coding port 'utf-8)
      (read-json port))))

(define (read-json port)
  (define (fail reason)
    (error "Error reading JSON" reason))

  (define (peek) (peek-char port))
  (define (take) (read-char port))

  (define (expect value expected)
    (unless (equal? value expected)
      (fail (string-append "Expected " (string expected)))))

  (define (skip-whitespace)
    (when (member (peek) '(#\space #\tab #\newline #\return))
      (take)
      (skip-whitespace)))

  (define (read-string)
    (expect (take) #\")
    (let loop ((chars '()))
      (let ((char (take)))
        (cond
          ((eof-object? char) (fail "Unterminated string"))
          ((char=? char #\") (list->string (reverse chars)))
          ((char=? char #\\)
           (let ((escaped
                   (case (take)
                     ((#\") #\")
                     ((#\\) #\\)
                     ((#\/) #\/)
                     ((#\n) #\newline)
                     ((#\r) #\return)
                     ((#\t) #\tab)
                     (else (fail "Invalid string escape")))))
             (loop (cons escaped chars))))
          ((< (char->integer char) 32)
           (fail "Unescaped control character in string"))
          (else (loop (cons char chars)))))))

  (define (read-number)
    (let loop ((chars '()))
      (let ((char (peek)))
        (if (or (eof-object? char)
                (member char '(#\space #\tab #\newline #\return #\, #\] #\})))
          (string->number (list->string (reverse chars)))
          (loop (cons (take) chars))))))

  (define (read-array)
    (expect (take) #\[)
    (skip-whitespace)
    (if (equal? (peek) #\])
      (begin (take) '())
      (let loop ((items '()))
        (let ((item (read-value)))
          (skip-whitespace)
          (case (take)
            ((#\]) (reverse (cons item items)))
            ((#\,) (loop (cons item items)))
            (else (fail "Expected comma or closing bracket")))))))

  (define (read-object)
    (expect (take) #\{)
    (skip-whitespace)
    (if (equal? (peek) #\})
      (begin (take) '())
      (let loop ((entries '()))
        (skip-whitespace)
        (let ((key (read-string)))
          (skip-whitespace)
          (expect (take) #\:)
          (let ((value (read-value)))
            (skip-whitespace)
            (case (take)
              ((#\}) (reverse (cons (cons key value) entries)))
              ((#\,) (loop (cons (cons key value) entries)))
              (else (fail "Expected comma or closing brace"))))))))

  (define (read-value)
    (skip-whitespace)
    (case (peek)
      ((#\") (read-string))
      ((#\[) (read-array))
      ((#\{) (read-object))
      ((#\- #\0 #\1 #\2 #\3 #\4 #\5 #\6 #\7 #\8 #\9) (read-number))
      (else (fail "Unsupported value"))))

  (read-value))
